export type MaterialCatalogItem = {
  canonicalName: string;
  displayName: string;
  aliases: string[];
  category: string;
  defaultUnit: string;
  safetyFlags?: string[];
};

export const STATIC_MATERIAL_CATALOG: MaterialCatalogItem[] = [
  {
    canonicalName: 'plastic_bottle',
    displayName: 'Chai nhựa',
    aliases: ['plastic bottle', 'chai nhua', 'chai nước', 'chai nuoc'],
    category: 'container',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'paper_cup',
    displayName: 'Ly giấy',
    aliases: ['paper cup', 'cup giấy', 'ly giay'],
    category: 'container',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'plastic_cup',
    displayName: 'Ly nhựa',
    aliases: ['plastic cup', 'cup nhựa', 'ly nhua'],
    category: 'container',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'cardboard',
    displayName: 'Bìa carton',
    aliases: ['cardboard', 'carton', 'bìa cứng', 'bia carton'],
    category: 'structure',
    defaultUnit: 'tấm',
  },
  {
    canonicalName: 'paper',
    displayName: 'Giấy',
    aliases: ['paper', 'printer paper', 'giay', 'giấy A4'],
    category: 'structure',
    defaultUnit: 'tờ',
  },
  {
    canonicalName: 'rubber_band',
    displayName: 'Dây thun',
    aliases: ['rubber band', 'elastic band', 'dây chun', 'day thun'],
    category: 'elastic',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'string',
    displayName: 'Dây chỉ',
    aliases: ['string', 'thread', 'twine', 'dây', 'day chi'],
    category: 'connector',
    defaultUnit: 'đoạn',
  },
  {
    canonicalName: 'straw',
    displayName: 'Ống hút',
    aliases: ['straw', 'drinking straw', 'ong hut', 'ống hút nhựa'],
    category: 'tube',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'paper_clip',
    displayName: 'Kẹp giấy',
    aliases: ['paper clip', 'paperclip', 'kẹp giấy', 'kep giay'],
    category: 'metal',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'binder_clip',
    displayName: 'Kẹp bướm',
    aliases: ['binder clip', 'clip đen', 'kep buom'],
    category: 'clip',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'magnet',
    displayName: 'Nam châm',
    aliases: ['magnet', 'bar magnet', 'nam châm', 'nam cham'],
    category: 'magnetism',
    defaultUnit: 'cái',
    safetyFlags: ['Để xa thiết bị điện tử và thẻ từ.'],
  },
  {
    canonicalName: 'battery',
    displayName: 'Pin',
    aliases: ['battery', 'AA battery', 'pin tiểu', 'pin'],
    category: 'electricity',
    defaultUnit: 'viên',
    safetyFlags: ['Không tháo pin hoặc làm chập hai cực.'],
  },
  {
    canonicalName: 'copper_wire',
    displayName: 'Dây đồng',
    aliases: ['copper wire', 'wire', 'dây đồng', 'day dong'],
    category: 'electricity',
    defaultUnit: 'đoạn',
    safetyFlags: ['Chỉ dùng với nguồn điện thấp trong lớp học.'],
  },
  {
    canonicalName: 'led',
    displayName: 'Đèn LED',
    aliases: ['LED', 'light emitting diode', 'đèn led', 'den led'],
    category: 'electricity',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'balloon',
    displayName: 'Bóng bay',
    aliases: ['balloon', 'bong bay', 'bóng bay'],
    category: 'elastic',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'coin',
    displayName: 'Đồng xu',
    aliases: ['coin', 'đồng xu', 'dong xu'],
    category: 'weight',
    defaultUnit: 'đồng',
  },
  {
    canonicalName: 'wooden_stick',
    displayName: 'Que gỗ',
    aliases: ['wooden stick', 'craft stick', 'popsicle stick', 'que gỗ'],
    category: 'structure',
    defaultUnit: 'que',
  },
  {
    canonicalName: 'ruler',
    displayName: 'Thước kẻ',
    aliases: ['ruler', 'plastic ruler', 'thước', 'thuoc ke'],
    category: 'measurement',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'tape',
    displayName: 'Băng dính',
    aliases: ['tape', 'adhesive tape', 'scotch tape', 'băng keo', 'bang dinh'],
    category: 'connector',
    defaultUnit: 'cuộn',
  },
  {
    canonicalName: 'scissors',
    displayName: 'Kéo',
    aliases: ['scissors', 'kéo', 'keo cat'],
    category: 'tool',
    defaultUnit: 'cái',
    safetyFlags: ['Cần giáo viên giám sát khi học sinh nhỏ sử dụng.'],
  },
  {
    canonicalName: 'rubber_stopper',
    displayName: 'Nút cao su',
    aliases: ['rubber stopper', 'nút cao su', 'nut cao su'],
    category: 'labware',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'syringe',
    displayName: 'Ống tiêm nhựa',
    aliases: ['plastic syringe', 'syringe', 'ống tiêm', 'ong tiem'],
    category: 'fluid',
    defaultUnit: 'cái',
    safetyFlags: ['Chỉ dùng ống tiêm không kim.'],
  },
  {
    canonicalName: 'marble',
    displayName: 'Viên bi',
    aliases: ['marble', 'ball', 'viên bi', 'vien bi'],
    category: 'motion',
    defaultUnit: 'viên',
  },
  {
    canonicalName: 'spoon',
    displayName: 'Muỗng',
    aliases: ['spoon', 'plastic spoon', 'muỗng', 'thìa'],
    category: 'tool',
    defaultUnit: 'cái',
  },
  {
    canonicalName: 'rubber_tube',
    displayName: 'Ống cao su',
    aliases: ['rubber tube', 'tube', 'ống cao su', 'ong cao su'],
    category: 'tube',
    defaultUnit: 'đoạn',
  },
  {
    canonicalName: 'cloth',
    displayName: 'Vải',
    aliases: ['cloth', 'fabric', 'vải', 'vai'],
    category: 'surface',
    defaultUnit: 'mảnh',
  },
  {
    canonicalName: 'aluminum_foil',
    displayName: 'Giấy bạc',
    aliases: ['aluminum foil', 'foil', 'giấy bạc', 'giay bac'],
    category: 'metal',
    defaultUnit: 'tờ',
  },
  {
    canonicalName: 'water',
    displayName: 'Nước',
    aliases: ['water', 'nước', 'nuoc'],
    category: 'fluid',
    defaultUnit: 'ml',
  },
];
